### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by ktym4a**
I feel these were typos and have corrected them.

### CODE REVIEW

**Review by florian-lefebvre — COMMENTED** [review]
I'm not against it, I just feel like it's a matter of personal preferences. I'm used to camelCase but why not PascalCase! Do you have a link to the zod docs where it's recommended or to several astro core/integrations using PascalCase? I'm just trying to see what's most used

**Comment by ktym4a** [comment]
oh, sorry.
I thought it should be aligned with `OptionsSchema` or `optionsSchema`.

```ts
const OptionsSchema = z.object({
    foo: z.union([z.array(z.string()), z.literal(undefined)]).optional()
})

type Options = {
    /** An insightful comment */
    foo?: z.infer<typeof OptionsSchema>["foo"]
}

export default defineIntegration({
    setup({ options: inputOptions }) {
        const options = optionsSchema.parse(inputOptions);

        return {}
    }
})
```

**Comment by florian-lefebvre** [comment]
Sorry!! I actually completely misread your PR, was on phone 😅. Looking at https://github.com/withastro/starlight/blob/main/packages/starlight/utils/user-config.ts, I think we should use `OptionsSchema` as the variable name. Can you update line 88 instead?

**Comment by ktym4a** [comment]
I apologize for my lack of explanation! I changed it to PascalCase.

**Review by florian-lefebvre — APPROVED** [review]
LGTM! Thanks for contributing 🚀

**Pull request merged**
