### PR TITLE
feat!: add support for subtyping and extra integration fields

### PR DESCRIPTION
**Pull request by Fryuni**

### CODE REVIEW

**Review by florian-lefebvre — CHANGES_REQUESTED** [review]
Can you improve the changeset and update the upgrade guide? Other than that, LGTM!

**Comment by Fryuni** [comment]
🎉 Great, will do so

**Comment by BryceRussell** [comment]
The highlighting on all the code blocks need to be updated as well

**Review by florian-lefebvre — APPROVED** [review]

**Review by BryceRussell — APPROVED** [review]
LGTM! (I squeezed in two small fixes I found in docs, I hope that is ok)

**Pull request merged**
